application:
  name: '@project.name@'
  artifactId: '@project.artifactId@'
  version: '@project.version@'
spring:
  profiles.active: default
  pid.fail-on-write-error: true
  pid.file: /packages/config/${application.artifactId}/${application.artifactId}.pid
server:
  port: 8090
logging:
  level.root: info
  level.io.exnihilo: debug
  file: /packages/logs/${application.artifactId}/${application.artifactId}.log
management:
  endpoints:
    web.exposure.include: "*"
    web.exposure.exclude: loggers
  endpoint:
    shutdown.enabled: true

---
#This section contains the properties that will be over-written for the Docker environment
spring:
  profiles: openshift
  pid.fail-on-write-error: true
  pid.file: ${application.artifactId}.pid
server:
  port: 8080
logging:
  level.root: info
  level.io.exnihilo: info
  file: logs/${application.artifactId}.log
